#!/bin/bash

echo "🚀 FitLife Pro - Quick Free Deployment Guide"
echo ""
echo "Choose your preferred free hosting platform:"
echo ""
echo "1) Vercel (Recommended) - https://vercel.com"
echo "2) Render - https://render.com"
echo "3) Fly.io - https://fly.io"
echo "4) Netlify - https://netlify.com"
echo "5) Manual Docker - docker run"
echo ""
read -p "Enter choice (1-5): " choice

case $choice in
    1)
        echo "🎯 Vercel Deployment"
        echo ""
        echo "Step 1: Push code to GitHub"
        echo "   git init"
        echo "   git add ."
        echo "   git commit -m 'Initial commit'"
        echo "   git remote add origin https://github.com/YOUR_USERNAME/fitlifepro.git"
        echo "   git branch -M main"
        echo "   git push -u origin main"
        echo ""
        echo "Step 2: Deploy on Vercel"
        echo "   1. Go to https://vercel.com"
        echo "   2. Sign in with GitHub"
        echo "   3. Click 'Add New Project'"
        echo "   4. Select 'fitlifepro' repository"
        echo "   5. Click 'Deploy'"
        echo ""
        echo "Step 3: Get PostgreSQL (Free)"
        echo "   1. Go to https://supabase.com"
        echo "   2. Create free account"
        echo "   3. Create new project"
        echo "   4. Get connection string"
        echo "   5. Add to Vercel Environment Variables"
        echo ""
        echo "✅ Complete in ~20 minutes"
        echo "💰 Cost: $0/month"
        ;;

    2)
        echo "🎯 Render Deployment"
        echo ""
        echo "Step 1: Push code to GitHub"
        echo "   git init"
        echo "   git add ."
        echo "   git commit -m 'Initial commit'"
        echo "   git remote add origin https://github.com/YOUR_USERNAME/fitlifepro.git"
        echo "   git push -u origin main"
        echo ""
        echo "Step 2: Deploy PostgreSQL"
        echo "   1. Go to https://render.com"
        echo "   2. Click 'New +' → 'Postgres Database'"
        echo "   3. Create 'fitlifepro-db'"
        echo "   4. Get connection string"
        echo ""
        echo "Step 3: Deploy Web App"
        echo "   1. Click 'New +' → 'Web Service'"
        echo "   2. Connect to GitHub"
        echo "   3. Build: npm install && npm run build"
        echo "   4. Start: npm start"
        echo "   5. Add env variables"
        echo "   6. Click 'Create Web Service'"
        echo ""
        echo "✅ Complete in ~30 minutes"
        echo "💰 Cost: $0/month"
        ;;

    3)
        echo "🎯 Fly.io Deployment"
        echo ""
        echo "Step 1: Install Fly CLI"
        echo "   curl -L https://fly.io/install.sh | sh"
        echo "   fly auth login"
        echo ""
        echo "Step 2: Deploy"
        echo "   cd /Users/apple/Documents/deepseek"
        echo "   fly launch"
        echo "   fly deploy"
        echo ""
        echo "Step 3: Add PostgreSQL"
        echo "   fly postgres create"
        echo "   fly postgres attach"
        echo ""
        echo "✅ Complete in ~15 minutes"
        echo "💰 Cost: $0/month"
        ;;

    4)
        echo "🎯 Netlify Deployment"
        echo ""
        echo "Step 1: Push code to GitHub"
        echo "   git init"
        echo "   git add ."
        echo "   git commit -m 'Initial commit'"
        echo "   git remote add origin https://github.com/YOUR_USERNAME/fitlifepro.git"
        echo "   git push -u origin main"
        echo ""
        echo "Step 2: Deploy on Netlify"
        echo "   1. Go to https://netlify.com"
        echo "   2. Sign in with GitHub"
        echo "   3. Click 'Add new site' → 'Import from Git'"
        echo "   4. Select 'fitlifepro' repository"
        echo "   5. Click 'Deploy site'"
        echo ""
        echo "Step 3: Add PostgreSQL"
        echo "   Get free PostgreSQL from Supabase or Railway"
        echo "   Add connection string as env variable"
        echo ""
        echo "✅ Complete in ~15 minutes"
        echo "💰 Cost: $0/month"
        ;;

    5)
        echo "🐳 Docker Deployment"
        echo ""
        echo "Step 1: Build Docker Image"
        echo "   docker build -t fitlifepro ."
        echo ""
        echo "Step 2: Run Container"
        echo "   docker run -d \\"
        echo "     -p 3000:3000 \\"
        echo "     -e DATABASE_URL='your-database-url' \\"
        echo "     -e AUTH_SECRET='your-secret' \\"
        echo "     -e NEXTAUTH_SECRET='your-secret' \\"
        echo "     fitlifepro"
        echo ""
        echo "✅ Complete in ~5 minutes"
        echo "💰 Cost: $0 (local) or VPS hosting cost"
        ;;

    *)
        echo "❌ Invalid choice. Please run the script again."
        exit 1
        ;;
esac

echo ""
echo "📚 For detailed guides, see FREE_DEPLOYMENT.md"
echo ""
echo "🎯 Ready to deploy! Good luck! 🚀"