"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, Ruler, Scale } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/components/ui/use-toast";

type Measurement = { id: string; date: string; weightKg: number | null; bodyFatPercent: number | null; chestCm: number | null; waistCm: number | null };
const fields = [["weightKg", "Weight", "kg", "70.5"], ["bodyFatPercent", "Body fat", "%", "15"], ["chestCm", "Chest", "cm", "100"], ["waistCm", "Waist", "cm", "85"], ["hipCm", "Hip", "cm", "95"], ["armCm", "Arm", "cm", "35"], ["thighCm", "Thigh", "cm", "55"], ["calfCm", "Calf", "cm", "38"]] as const;

export default function ProgressPage() {
  const { toast } = useToast(); const [measurements, setMeasurements] = useState<Measurement[]>([]); const [form, setForm] = useState<Record<string, string>>({}); const [isSaving, setIsSaving] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/measurements", { cache: "no-store" }); if (response.ok) setMeasurements((await response.json()).measurements); }, []);
  useEffect(() => { void load(); }, [load]); const latest = measurements[0];
  async function save() { setIsSaving(true); try { const response = await fetch("/api/measurements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setForm({}); await load(); toast({ title: "Progress saved", description: "Your measurement has been added to your history." }); } catch (error) { toast({ title: "Couldn’t save", description: error instanceof Error ? error.message : "Please try again.", variant: "destructive" }); } finally { setIsSaving(false); } }
  return <div className="space-y-6 page-enter"><div><p className="eyebrow">Your journey</p><h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">Progress</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Measure what matters and celebrate the trend.</p></div><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Scale />} label="Current weight" value={latest?.weightKg ? `${latest.weightKg} kg` : "—"} detail="Latest check-in" delay="0ms" /><Stat icon={<Activity />} label="Body fat" value={latest?.bodyFatPercent != null ? `${latest.bodyFatPercent}%` : "—"} detail="Latest check-in" delay="70ms" /><Stat icon={<Ruler />} label="Measurements" value={String(measurements.length)} detail="Recent records" delay="140ms" /></div><Card className="motion-card" style={{ animationDelay: "210ms" }}><CardHeader><CardTitle>New check-in</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{fields.map(([key, label, unit, placeholder]) => <div key={key} className="space-y-2"><Label htmlFor={key}>{label} <span className="text-slate-400">({unit})</span></Label><Input id={key} type="number" min="0" max="999" step="0.1" placeholder={placeholder} value={form[key] ?? ""} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} /></div>)}</div><Button className="mt-6" disabled={isSaving} onClick={() => void save()}>Save check-in</Button></CardContent></Card><Card className="motion-card" style={{ animationDelay: "280ms" }}><CardHeader><CardTitle>History</CardTitle></CardHeader><CardContent>{measurements.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{measurements.map((item) => <div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="font-medium text-slate-900 dark:text-white">{new Date(item.date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p><div className="flex flex-wrap gap-x-6 gap-y-1 text-sm text-slate-600 dark:text-slate-300">{item.weightKg != null && <span><strong className="text-slate-900 dark:text-white">{item.weightKg} kg</strong> weight</span>}{item.bodyFatPercent != null && <span><strong className="text-slate-900 dark:text-white">{item.bodyFatPercent}%</strong> body fat</span>}{item.chestCm != null && <span><strong className="text-slate-900 dark:text-white">{item.chestCm} cm</strong> chest</span>}{item.waistCm != null && <span><strong className="text-slate-900 dark:text-white">{item.waistCm} cm</strong> waist</span>}</div></div>)}</div> : <p className="py-12 text-center text-slate-500">Your measurements will appear here after your first check-in.</p>}</CardContent></Card></div>;
}

function Stat({ icon, label, value, detail, delay }: { icon: React.ReactNode; label: string; value: string; detail: string; delay: string }) { return <Card className="motion-card" style={{ animationDelay: delay }}><CardContent className="pt-6"><div className="flex items-center justify-between text-slate-500"><p className="text-sm font-medium">{label}</p><span className="h-8 w-8 rounded-full bg-primary/10 p-2 text-primary">{icon}</span></div><p className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></CardContent></Card>; }
